version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "8081:80"
        volumes:
            - ./Projects:/var/www/html/:z
            - ./conf.d:/etc/nginx/conf.d/:z
            - ./logs:/log:z
        network_mode: host

    phpfpm:
        build: ./phpfpm
        ports:
            - "9000:9000"
            - "9999:9999"
        volumes:
            - ./Projects:/var/www/html:z
        network_mode: host

    mysql:
        build: ./mysql
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql/:z
        environment:
            MYSQL_DATABASE: local_pricing
            MYSQL_ROOT_PASSWORD : 123456
        network_mode: bridge